def URL
def BRANCH
def CREDENTIALS

pipeline {
  agent { label 'swarm' }
  stages {
    stage ('Checkout') {
      steps {
        script {
          URL='http://gitlab.rindecuentas.org/equipo-qqw/poppins.git'
          BRANCH='*/feature/nifi_cluster'
          CREDENTIALS='f28cf2d5-ce55-4f0b-9bad-c84376ce401d'
        }
          dir('new-dir') { sh 'pwd' }
          ansiColor('xterm') {
            checkout changelog: false, poll: false, scm:
            [$class:
             'GitSCM', branches: [[name: BRANCH]],
              doGenerateSubmoduleConfigurations: false,
              extensions: [],
              submoduleCfg: [],
              userRemoteConfigs:
              [[
                credentialsId: CREDENTIALS,
                url: URL
              ]]
            ]
          }
        echo "Clean container and Image"
        sh 'cd registry; make clean'
      }
    }
    stage ('Build Image') {
      agent { label 'swarm' }
      steps {
        script {
          echo "Build container"
          sh 'cd registry; make build'
        }
      }
    }
    stage ('Test Image') {
      agent { label 'swarm' }
      steps {
        script {
          echo "Test container"
          sh 'cd registry; make test'
        }
      }
    }
    stage ('Release Image') {
      agent { label 'swarm' }
      steps {
        script {
          echo "Push container image to dockerhub registry"
          sh 'cd registry; make release'
	        echo "Clean container ans Image"
	        sh 'cd registry; make clean'
        }
      }
    }
  }
}
