#!/bin/bash

source /var/lib/jenkins/.env

POPPINS_ORG_NAME=poppins
POPPINS_APP_NAME=poppins
POPPINS_VERSION=0.3.0
# POPPINS_VERSION=$(cat package.json | jq -r .version)
POPPINS_DOCKER_REPO=${DOCKER_REPO}/${POPPINS_ORG_NAME}:${POPPINS_VERSION}
APPS_DATA_FILE=/var/lib/jenkins/apps_data

[[ ! -f "$APPS_DATA_FILE" ]] && touch $APPS_DATA_FILE
chown jenkins:jenkins $APPS_DATA_FILE;

sed -i \
 -e '/^POPPINS_VERSION/ d'  \
 -e '/^POPPINS_ORG_NAME/ d' \
 -e '/^POPPINS_APP_NAME/ d' \
 -e '/^POPPINS_DOCKER_REPO/ d' \
$APPS_DATA_FILE
echo "POPPINS_VERSION=$POPPINS_VERSION" >> $APPS_DATA_FILE
echo "POPPINS_ORG_NAME=$POPPINS_ORG_NAME" >> $APPS_DATA_FILE
echo "POPPINS_APP_NAME=$POPPINS_APP_NAME" >> $APPS_DATA_FILE
echo "POPPINS_DOCKER_REPO=$POPPINS_DOCKER_REPO" >> $APPS_DATA_FILE
